### ISSUE TITLE
Wikipedia now enforces HTTPS

### ISSUE THREAD

**Issue by petersandor** [natetyler/wikiquotes-api#6]
Hi, this module is still using [HTTP as the base API url](https://github.com/natetyler/wikiquotes-api/blob/15c41b3874035d57c4fc19a5b742afa2dd463852/wikiquote-api.js#L5) , so the example app doesn't work for me because Chrome blocks this request.

Also the API response format seems to be changed, so even when it gets the response it can't parse it.

**Comment by natetyler** [comment]
#5 fixed the https issue. With that in place I'm not seeing any errors, can you be more specific on the API change?

**Comment by petersandor** [comment]
Thanks for looking into this. The error appears only in Firefox (in my case with some hardened security settings with JSONP disabled), it's okay when I try it on Chrome.
